image: ghcr.io/cirruslabs/flutter:3.22.0

stages:
  - build

build:
  stage: build
  script:
    - apt-get -qq update && apt-get -qq install openjdk-17-jdk
    - update-alternatives --set java $(update-alternatives --list java | grep java-17)
    - update-alternatives --set javac $(update-alternatives --list javac | grep java-17)
    - flutter doctor
    - flutter pub get
    - flutter analyze
    - cd example
    - flutter build apk
  only:
    - master
    - tags
    - merge_requests
  tags:
    - generic-ash-intel
